## <font color = darkblue> Examples for Ball Tree and KDTree
- This code uses House Prices data as example


In [39]:
# ----------------------------------------
# Importing the necessary libraries
# ----------------------------------------

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns
import warnings
from datetime import datetime
warnings.filterwarnings('ignore') 
sns.set(rc={'figure.figsize':(11,8)})
# pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.options.display.float_format = '{:.2f}'.format

%cd "/Volumes/LACIE SHARE/Courses/Roux /Machine Learning/Assignments/Assignment 3"

# ----------------------------
# Loading the dataset
# ----------------------------
df = pd.read_csv('HousePrice.csv')

# --------------
# Dropping NAs
# --------------
df = df.dropna()


/Volumes/LACIE SHARE/Courses/Roux /Machine Learning/Assignments/Assignment 3


## <font color = darkblue>  Ball tree and KD Tree

In [48]:
import numpy as np
from sklearn.neighbors import BallTree
from sklearn.neighbors import KDTree

rng = np.random.RandomState(0)
X = rng.random_sample((1000000, 100))  # 10 rows in 3 dimensions

print(X)
print("time", datetime.now().strftime("%H:%M:%S"))
ball = BallTree(X, leaf_size=2)              
dist_ball, ind_ball = ball.query(X[1:2], k=5)  
print(f"Ball tree: the nearest indices to Row 2 are: {ind_ball}, \nAnd the respective distances are: {dist_ball}")

print("\n\n")
print("time", datetime.now().strftime("%H:%M:%S"))
kd = KDTree(X, leaf_size=2)              
dist_kd, ind_kd = kd.query(X[1:2], k=5)                
print(f'''KD Tree: the nearest indices to Row 2 are: {ind_kd}, \nAnd the respective distances are: 
      {dist_kd}''')
print("time", datetime.now().strftime("%H:%M:%S"))

[[0.5488135  0.71518937 0.60276338 ... 0.02010755 0.82894003 0.00469548]
 [0.67781654 0.27000797 0.73519402 ... 0.25435648 0.05802916 0.43441663]
 [0.31179588 0.69634349 0.37775184 ... 0.86219152 0.97291949 0.96083466]
 ...
 [0.68782167 0.90092168 0.66774824 ... 0.50405791 0.17589471 0.10361258]
 [0.48840402 0.24274619 0.62764525 ... 0.31754888 0.41230187 0.41578999]
 [0.59087167 0.81092671 0.50416045 ... 0.08870192 0.45256207 0.17769845]]
time 13:44:07
Ball tree: the nearest indices to Row 2 are: [[     1 209407 378457 461797 531203]], 
And the respective distances are: [[0.         2.88711025 2.94141286 2.97841873 2.99664155]]



time 13:44:33
KD Tree: the nearest indices to Row 2 are: [[     1 209407 378457 461797 531203]], 
And the respective distances are: 
      [[0.         2.88711025 2.94141286 2.97841873 2.99664155]]
time 13:45:01
